// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testItem.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestItem struct {
	// 物品Id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 物品名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 物品类型
	ItemType int32 `protobuf:"varint,3,opt,name=itemType,proto3" json:"itemType,omitempty"`
	// 初始物品数量
	Number               int32    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestItem) Reset()         { *m = TestItem{} }
func (m *TestItem) String() string { return proto.CompactTextString(m) }
func (*TestItem) ProtoMessage()    {}
func (*TestItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab9b992c72e934b6, []int{0}
}

func (m *TestItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestItem.Unmarshal(m, b)
}
func (m *TestItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestItem.Marshal(b, m, deterministic)
}
func (m *TestItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestItem.Merge(m, src)
}
func (m *TestItem) XXX_Size() int {
	return xxx_messageInfo_TestItem.Size(m)
}
func (m *TestItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TestItem.DiscardUnknown(m)
}

var xxx_messageInfo_TestItem proto.InternalMessageInfo

func (m *TestItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestItem) GetItemType() int32 {
	if m != nil {
		return m.ItemType
	}
	return 0
}

func (m *TestItem) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type TestItem_Array struct {
	Items                []*TestItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TestItem_Array) Reset()         { *m = TestItem_Array{} }
func (m *TestItem_Array) String() string { return proto.CompactTextString(m) }
func (*TestItem_Array) ProtoMessage()    {}
func (*TestItem_Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab9b992c72e934b6, []int{1}
}

func (m *TestItem_Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestItem_Array.Unmarshal(m, b)
}
func (m *TestItem_Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestItem_Array.Marshal(b, m, deterministic)
}
func (m *TestItem_Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestItem_Array.Merge(m, src)
}
func (m *TestItem_Array) XXX_Size() int {
	return xxx_messageInfo_TestItem_Array.Size(m)
}
func (m *TestItem_Array) XXX_DiscardUnknown() {
	xxx_messageInfo_TestItem_Array.DiscardUnknown(m)
}

var xxx_messageInfo_TestItem_Array proto.InternalMessageInfo

func (m *TestItem_Array) GetItems() []*TestItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*TestItem)(nil), "pb.testItem")
	proto.RegisterType((*TestItem_Array)(nil), "pb.testItem_Array")
}

func init() { proto.RegisterFile("testItem.proto", fileDescriptor_ab9b992c72e934b6) }

var fileDescriptor_ab9b992c72e934b6 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x49, 0x2d, 0x2e,
	0xf1, 0x2c, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x4a,
	0xe2, 0xe2, 0x80, 0x89, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x06, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x52, 0x5c, 0x1c, 0x99, 0x25, 0xa9, 0xb9, 0x21, 0x95, 0x05,
	0xa9, 0x12, 0xcc, 0x60, 0x95, 0x70, 0xbe, 0x90, 0x18, 0x17, 0x5b, 0x5e, 0x69, 0x6e, 0x52, 0x6a,
	0x91, 0x04, 0x0b, 0x58, 0x06, 0xca, 0x53, 0x32, 0x41, 0xd8, 0x1c, 0xef, 0x58, 0x54, 0x94, 0x58,
	0x29, 0xa4, 0xc4, 0xc5, 0x0a, 0xd2, 0x55, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa3,
	0x57, 0x90, 0xa4, 0x07, 0x53, 0x12, 0x04, 0x91, 0x4a, 0x62, 0x03, 0x3b, 0xd2, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x98, 0xe2, 0x95, 0x7b, 0xb6, 0x00, 0x00, 0x00,
}
